// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpphgpwvwsiabbiqubyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwcGhncHd2d3NpYWJiaXF1YnlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MDgyNDgsImV4cCI6MjA3MDQ4NDI0OH0.QQJ6MCiOr4qnwu3nB4rnM-jqQp4hKzVPDQfSXk3WAXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});